import { faHtml5 } from '@fortawesome/free-brands-svg-icons';
import React from 'react';


interface Project {Title: string, Description: string, Link: string, Image: string, Languages: string[], Frameworks: string[], Tags: string[], Year: number, Index: number};

const ProjectsList: Project[] = [
    {Title: 'C-Sharp-Calculator', Description: 'A simple calculator made in C#', Link: 'https://github.com/Vaporjawn/C-Sharp-Calculator', Image: 'https://raw.githubusercontent.com/Vapor-jawn/Instagram-Pictures/main/images/CodingProject.jpg.jpg', Languages: ['C#'], Frameworks: ['.NET'], Tags: ['calculator', 'csh', 'csharp', 'equation', 'csharp-code', 'csharp-script', 'csharp-core', 'csharp-library', 'csharp7', 'cshtml', 'cshap'], Year: 2020, Index: 1},
    {Title: 'Checkers', Description: 'The classic game of checkers made using HTML5 and Javascript', Link: 'https://github.com/Vaporjawn/Checkers', Image: 'https://raw.githubusercontent.com/Vapor-jawn/Instagram-Pictures/main/images/CodingProject.jpg.jpg', Languages: ['Javascript','HTML','CSS'], Frameworks: ['JQuery','SASS','HTML5'], Tags: ['css', 'game', 'sass', 'jquery', 'board-game', 'html5', 'favicon', 'classic', 'boardgame', 'checkers', 'vaporjawn'], Year: 2020, Index: 2},
    {Title: 'Graphing-Calculator', Description: 'A fully functioning graphing calculator made out of JavaScript', Link: 'https://github.com/Vaporjawn/Graphing-Calculator', Image: 'https://github.com/Vaporjawn/Graphing-Calculator/raw/master/website.png', Languages: ['Javascript','HTML'], Frameworks: ['Bootstrap'], Tags: ['javascript', 'calculator', 'calculator-application', 'calculator-javascript', 'calculator-application', 'calculator-app',], Year: 2020, Index: 3},
    {Title: 'Javascript-Calculator', Description: 'A Calculator made out of Javascript and ES6', Link: 'https://github.com/Vaporjawn/Javascript-Calculator', Image: 'https://github.com/Vaporjawn/Javascript-Calculator/raw/master/website.png', Languages: ['Javascript','HTML','CSS'], Frameworks: ['Bootstrap'], Tags: ['javascript', 'css', 'html', 'calculator', 'html5', 'script', 'javascript-calculator', 'caclulator'], Year: 2020, Index: 4},
    {Title: 'Maze.JS', Description: 'A maze generator made out of JavaScript', Link: 'https://github.com/Vaporjawn/Maze.JS', Image: 'https://github.com/Vaporjawn/Maze.JS/raw/master/website.png', Languages: ['Javascript'], Frameworks: ['P5'], Tags: ['javascript', 'maze', 'maze-generator', 'maze-algorithms', 'maze-game', 'mazes', 'maze-solver', 'maze-creation', 'maze-generation-algorithms', 'mazerunner', 'maze-explorer'], Year: 2020, Index: 5},
    {Title: 'Mock-Store', Description: 'A webapp UI skeleton for a software store', Link: 'https://github.com/Vaporjawn/Mock-Store', Image: 'https://raw.githubusercontent.com/Vapor-jawn/Instagram-Pictures/main/images/CodingProject.jpg.jpg', Languages: ['Javascript','HTML','CSS'], Frameworks: ['JQuery','SASS','HTML5'], Tags: ['Mock', 'Store'], Year: 2020, Index: 6},
    {Title: 'Prime-Number-Finder', Description: 'A java program that finds prime numbers', Link: 'https://github.com/Vaporjawn/Prime-Number-Finder', Image: 'https://raw.githubusercontent.com/Vapor-jawn/Instagram-Pictures/main/images/CodingProject.jpg.jpg', Languages: ['Java'], Frameworks: ['NetBeans'], Tags: ['python', 'java', 'finder', 'prime', 'number', 'primenumbers', 'primenumbergenerator'], Year: 2016, Index: 7},
    {Title: 'React-Tac-Toe', Description: 'A tic tac toe game made in React', Link: 'https://github.com/Vaporjawn/React-Tac-Toe', Image: 'https://raw.githubusercontent.com/Vapor-jawn/Instagram-Pictures/main/images/CodingProject.jpg.jpg', Languages: ['Javascript','CSS'], Frameworks: ['React', 'JSX'], Tags: ['React', 'JSX'], Year: 2020, Index: 8},
    {Title: 'ShortURL', Description: 'ShortURL is, as the name suggests, a URL shortener that is comprised of JavaScript along with modules and views', Link: 'https://github.com/Vaporjawn/ShortURL', Image: 'https://github.com/Vaporjawn/Retro-Catch-the-Block/raw/master/website.png', Languages: ['EJS', 'JavaScript'], Frameworks: ['EJS'], Tags: ['EJS','URL'], Year: 2021, Index: 9},
    {Title: 'SNEK', Description: 'A remake of the classic Snake Game', Link: 'https://github.com/Vaporjawn/SNEK', Image: 'https://github.com/Vaporjawn/SNEK/raw/master/website.png', Languages: ['Javascript','HTML'], Frameworks: ['HTML5'], Tags: ['javascript', 'css', 'game', 'html', 'html5', 'snake', 'snake-game', 'fruit', 'snek', 'snakes'], Year: 2020, Index: 10}
];


export default ProjectsList;
